In [2]:
# 提取列表内大于阈值提取位置

import numpy as np
probs = np.array([[0, 0, 0, 0, 0, 1, 2], [1, 2, 2, 0, 0, 1, 2]])
a = np.array(probs >= 1, dtype='bool')
c = np.nonzero(a)
b = probs[a]
print(probs, '\n',a, '\n', c, '\n', b,)

[[0 0 0 0 0 1 2]
 [1 2 2 0 0 1 2]] 
 [[False False False False False  True  True]
 [ True  True  True False False  True  True]] 
 (array([0, 0, 1, 1, 1, 1, 1]), array([5, 6, 0, 1, 2, 5, 6])) 
 [1 2 1 2 2 1 2]


## list 删除元素
### 使用 del 删除指定元素

In [2]:
 li = ['A', 'B', 'C', 'D']
 del li[2]
 print(li)

['A', 'B', 'D']


使用 list 方法 remove 删除指定值的元素

可以删除指定元素

In [8]:
li = ['A', 'B', 'C', 'D']
li.remove('C')
print(li)

['A', 'B', 'D']


### 使用 pop 删除元素

In [4]:

li = ['A', 'B', 'C', 'D']
li.pop(2)
print(li)
print('~~~~~~~~~')
li.pop('A')

['A', 'B', 'D']
~~~~~~~~~


TypeError: 'str' object cannot be interpreted as an integer

### 使用切片删除元素

In [5]:
li = ['A', 'B', 'C', 'D']
li = li[:2] + li[3:]
print(li)

['A', 'B', 'D']


### 正确复制裂变的方法

In [9]:
import copy
a = [[10], 20]
b = a[:]
c = list(a)
d = a * 1
e = copy.copy(a)
f = copy.deepcopy(a)
a.append(21)
a[0].append(11)
print( id(a), a)
print('~~~~~~~~~~')
print( id(b), b)
print('~~~~~~~~~~')
print (id(c), c)
print('~~~~~~~~~~')
print (id(d), d)
print('~~~~~~~~~~')
print (id(e), e)
print('~~~~~~~~~~')
print (id(f), f)
print('~~~~~~~~~~')

4570806384 [[10, 11], 20, 21]
~~~~~~~~~~
4570806304 [[10, 11], 20]
~~~~~~~~~~
4570851120 [[10, 11], 20]
~~~~~~~~~~
4570806624 [[10, 11], 20]
~~~~~~~~~~
4570806464 [[10, 11], 20]
~~~~~~~~~~
4570806784 [[10], 20]
~~~~~~~~~~


从以上可以看出，使用 a[:], list(a), a*1, copy.copy(a)四种方式复制列表结果都可以得到一个新的列表，但是如果列表中含有列表，所有b, c, d, e四个新列表的子列表都是指引到同一个对象上。只有使用copy.deepcopy(a)方法得到的新列表f才是包括子列表在内的完全复制。

### python 如何找出两个list中的相同元素

可以bai对第二个list的元素进行遍历，检查是否出现在du第二个zhilist当中，如果使用表理dao解，可以使用一行代码完成任务。

In [18]:
list1 = [1,2,3,4,5]
list2 = [4,5,6,7,8]
print([l for l in list1 if l in list2])
# [4,5]
print('~~~~~~~~~~~~~~~~~~~~')
# 如果每一个列表中均没有重复的元素，那么还有另外一种更好的办法。首先把两个list转换成set，然后对两个set取交集，即可得到两个list的重复元素。

set1 = set(list1)
set2 = set(list2)
print(set1 & set2)

[4, 5]
~~~~~~~~~~~~~~~~~~~~
{4, 5}
